### ISSUE TITLE
Connector and car pins mapping 

### ISSUE THREAD

**Issue by Qwerty-OFF** [rusefi/proteus-mitsubishi76-adapter#10]
From 1 to 72 pins in connector:

TE official drawing

![image](https://user-images.githubusercontent.com/4116383/144751214-8481e94f-aecf-464d-95c8-0cca641d80bc.png)
and
1-26
31-46
51-62
71-92
on wiring diagrams. The number of contacts shows that these are separate sections of the connector. But how are the pins numbered within the section?

**Comment by rusefillc** [comment]
https://my.prostreetonline.com/2013/09/05/faq-1g-and-2g-dsm-ecu-pinouts/ has a good
