### ISSUE TITLE
jdm evo VII ecu the fuel pump pin should be pin 8 instead of pin 22

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-mitsubishi76-adapter#11]
Maurice says "jdm evo VII ecu the fuel pump pin should be pin 8 instead of pin 22"

**Comment by ElDominio** [comment]
some years swap the A/C clutch and fuel pump pins around, for reasons I don't know

**Comment by rusefillc** [comment]
@Qwerty-OFF please out a comment next to those pins

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/145275120-fbafa72a-7913-47c5-a154-619f7dbb5a2a.png)
