### ISSUE TITLE
VND14NV04  tab not connected? 

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-mitsubishi76-adapter#14]
should VND14NV04 tab be connected somewhere?

![image](https://user-images.githubusercontent.com/48498823/157049343-92306eb2-0237-47bc-9659-ca356a262a8a.png)

**Comment by Qwerty-OFF** [comment]
This is AUIPS2041LTR, not VND14NV04. In this case tab is not connected for compatibility with other lowside switches.

**Comment by rusefillc** [comment]
So for VND14NV04 usage example we have WBO mosfet?

**Comment by rusefillc** [comment]
Q600.

![image](https://user-images.githubusercontent.com/48498823/157471525-0aed9b27-df6c-41f8-9545-26073f61c4d3.png)
