### ISSUE TITLE
Idle stepper plan for Proteus

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-mitsubishi76-adapter#4]
I have six pin stepper idle

40 OHm between middle +12 wires and other ends of 80 OHm coils. Coils A and B seem to NOT be connecter.

My preference would be to use two Proteus H-bridges. What do I do with the middle +12?

What do I do about those being connected on the vehicle? would H-bridge plan not work until +12 middle pins are disconnected?

![image](https://user-images.githubusercontent.com/48498823/140138172-b2f29c22-fa53-4a03-a2d3-bfd5ad696642.png)

full schematics https://github.com/rusefi/rusefi/wiki/Vault-of-Mitsubishi#1995-3000gt

**Comment by rusefillc** [comment]
@andreika-git @mck1117 ^^^

**Comment by mck1117** [comment]
that's a unipolar stepper, not a bipolar stepper, so it needs yet another different control mode, and four lowside outputs

**Comment by mck1117** [comment]
![](https://www.ato.com/Content/Images/uploaded/unipolar-circuit-.jpg)

**Comment by rusefillc** [comment]
Would cutting those +12v wires make it a bipolar stepper?

**Comment by mck1117** [comment]
It may work, but it's not very PnP. It's possible the motor may be too weak if we rewired it as a bipolar stepper.

**Comment by rusefillc** [comment]
So we use four low sides for stepper coils great news we have those on Proteus

@mck1117 do we need fly-backs on those lines?

**Comment by rusefillc** [comment]
Let's see if we have enough Proteus low sides, let's add fly-backs on the board just in case.

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/145275274-9881ef85-212e-44dd-975a-e7a606c1083c.png)

**Comment by rusefillc** [comment]
@mck1117 does this look right?

**Comment by mck1117** [comment]
looks fine to me
