### ISSUE TITLE
Pin 71 question starting system

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-mitsubishi76-adapter#6]

**Comment by rusefillc** [comment]
See bottom of https://github.com/rusefi/rusefi/wiki/1995-3000gt

**Comment by rusefillc** [comment]
@ElDominio any idea what is pin 71? is it starter feedback into ECU which we do not care about?

**Comment by ElDominio** [comment]
From what I can remember, if you send 12v, the car cranks on that pin. Still works with the normal key even without an ECU present

**Comment by rusefillc** [comment]
So we just have a via and move on
