### ISSUE TITLE
coil control level

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-mitsubishi76-adapter#8]
5v or 12v or else?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/142963853-834390de-c2d9-4a97-8942-fcd81ab4fdbe.png)

**Comment by rusefillc** [comment]
@elElDominio what do you think? 5v or 12v?

**Comment by rusefillc** [comment]
Let's decide that 5v

**Comment by ElDominio** [comment]
It's 5v level
